
# We need ubuntu-wallpapers installed 
# apt install ubuntu-wallpapers
wallpaper {
    # Default to all monitors.
    monitor =
    path = /usr/share/backgrounds/ubuntu-wallpaper-d.png
    fit_mode = cover
}

splash = false
